name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adoptopenjdk'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run tests with Maven
        run: mvn test

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-artifact
          path: target/*.jar

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t phfontess/notification-service-worker:${{ github.sha }} .

      - name: Tag Docker Image
        run: |
          docker tag phfontess/notification-service-worker:${{ github.sha }} phfontess/notification-service-worker:latest

      - name: Push Docker Image
        run: |
          docker push phfontess/notification-service-worker:${{ github.sha }}
          docker push phfontess/notification-service-worker:latest